name:  Matrix

on: 
 push:
   
jobs:
  node-version:
    strategy:
      matrix:
        node_version: [6,8,10]
      #fail-fast: false
      #max-parallel: 0
    runs-on:  ubuntu-latest
    steps:
      - name: log out node version
        run:  node -v
      - name:  setup new node version
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ matrix.node_version }}
      - name: log out node version again
        run:  node -v